# Generated by Django 5.1.1 on 2024-10-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("sID", models.CharField(max_length=10)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sjID", models.CharField(max_length=10)),
                ("sName", models.CharField(max_length=100)),
                ("eduSec", models.CharField(max_length=1)),
                ("eduYear", models.IntegerField()),
                ("seatAva", models.IntegerField()),
            ],
        ),
    ]
