# Generated by Django 5.1.1 on 2024-10-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("sID", models.CharField(max_length=100)),
                ("sjID", models.CharField(max_length=10)),
                ("sName", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("sID", models.CharField(max_length=10)),
                ("idCard", models.CharField(max_length=13)),
                ("date", models.DateField(auto_now_add=True)),
                ("faculty", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sjID", models.CharField(max_length=10)),
                ("sName", models.CharField(max_length=100)),
                ("eduSec", models.CharField(max_length=1)),
                ("eduYear", models.IntegerField()),
                ("maxSeat", models.IntegerField()),
                ("seatAva", models.IntegerField()),
                ("status", models.BooleanField()),
                ("isPicked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TempRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("sID", models.CharField(max_length=100)),
                ("sjID", models.CharField(max_length=10)),
                ("sName", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.student"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.subject"
                    ),
                ),
            ],
        ),
    ]
