# Generated by Django 5.1.1 on 2024-10-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_regis_student_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="age",
        ),
    ]
