# Generated by Django 5.1.1 on 2024-10-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_subject_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="faculty",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
