# Generated by Django 5.1.1 on 2024-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_student_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
