# Generated by Django 5.1.1 on 2024-10-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_student_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("sID", models.CharField(max_length=10)),
                ("sjID", models.CharField(max_length=10)),
                ("sName", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Regis",
        ),
        migrations.AddField(
            model_name="subject",
            name="maxSeat",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
