# Generated by Django 5.1.1 on 2024-10-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_register_delete_regis_subject_maxseat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="fname",
        ),
        migrations.RemoveField(
            model_name="register",
            name="lname",
        ),
        migrations.RemoveField(
            model_name="register",
            name="sID",
        ),
        migrations.RemoveField(
            model_name="register",
            name="sName",
        ),
        migrations.RemoveField(
            model_name="register",
            name="sjID",
        ),
    ]
