# Generated by Django 5.1.1 on 2024-10-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_remove_register_fname_remove_register_lname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
