# Generated by Django 5.1.1 on 2024-10-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_tempregister"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="isPicked",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
