# Generated by Django 5.1.1 on 2024-10-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_subject_ispicked"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempregister",
            name="fname",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tempregister",
            name="lname",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tempregister",
            name="sID",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tempregister",
            name="sName",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tempregister",
            name="sjID",
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
