# Generated by Django 5.1.1 on 2024-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_tempregister_fname_tempregister_lname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="isPicked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subject",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
