# Generated by Django 5.1.1 on 2024-10-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_subject_ispicked_alter_subject_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="fname",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="lname",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="sID",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="sName",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="register",
            name="sjID",
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
