# Generated by Django 5.1.1 on 2024-10-05 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_register_fname_register_lname_register_sid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempregister",
            name="student",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.student",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tempregister",
            name="subject",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.subject",
            ),
            preserve_default=False,
        ),
    ]
