# Generated by Django 5.1.1 on 2024-10-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_tempregister_student_tempregister_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="status",
            field=models.BooleanField(),
        ),
    ]
